# Generated by Django 5.1.7 on 2025-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=100, unique=True)),
                ('nivel', models.IntegerField(default=1)),
                ('id_instructor', models.IntegerField(blank=True, null=True)),
                ('id_mascota', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
