# Generated by Django 5.1.7 on 2025-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
