POST http://127.0.0.1:8000/usuarios/crear/
Content-Type: application/json

{
    "nombre": "Juan Pérez",
    "nickName": "juan141",
    "nivel": 1,
    "id_instructor": "12321",
    "id_mascota": "1212"
}
